### ISSUE TITLE
Request: Customized Image Download Path

### ISSUE THREAD

**Issue by iplaywind** [fnya/media-sync#1]
The MediaSync plugin provides a great image download feature, but the downloaded images are saved in the "_media-sync_resouces" folder, which is not ideal for file management. Could you please add different options so that users can set their preferred download path for images?
In other words, when pasting local images into Obsidian, according to Obsidian's settings, the images are saved in the corresponding folder. For the MediaSync plugin, it would be great if it could follow a similar approach and automatically download images to the attachment folder set in Obsidian's settings.

**Comment by fnya** [comment]
@iplaywind 
Implemented in version 0.0.7. Please try it.
https://github.com/fnya/media-sync/releases/tag/0.0.7
