### ISSUE TITLE
Doesn't work with twitter urls?

### ISSUE THREAD

**Issue by CMC-3D** [fnya/media-sync#12]
I have 500 notes with urls, most of them not twitters. Tried it with the leaf icon and it does download images succesfully (with the obsidian attachment folder option being checked, otherwise with default it shows this which is my current):

![image](https://github.com/user-attachments/assets/ed66ca1b-69fd-4270-9483-871fdd52e666)

Though, the original twitter urls don't seem to be updated after it finishes, I did reopen obsidian but nothing happens? Tried it with the right click option and the same occurs, idk if I am missing something or need to manually drag downloaded images,

![image](https://github.com/user-attachments/assets/579eae32-260c-4e4a-b3c7-1eb2363a1f11)

example url as shown:
https://twitter.com/BeyondExtent/status/1536045749305323522

**Comment by fnya** [comment]
@CMC-3D 
Twitter is not covered by Media Sync. Therefore, it cannot be downloaded.
