### ISSUE TITLE
Once an image file has been downloaded, the Markdown file will not be processed the next time.

### ISSUE THREAD

**Issue by g33k247** [fnya/media-sync#2]
I'm seeing some odd behavior with the plugin. I have around 1,577 notes in my Obsidian. When I start the plugin, it shows me "Media Sync in Process!", "Media Sync in Pocess!! (1/1577)" and so on.

Note: Recommend that these notifications be expired after 10 seconds, rather forcing the user to manually dismiss them.

What I've noticed is the Media Sync will count up to around 150-190, then it seems to stop or timeout without producing other notifications or an error.

**Comment by fnya** [comment]
@g33k247 
For now, version 0.0.8 has improved notifications.
https://github.com/fnya/media-sync/releases/tag/0.0.8

**Comment by g33k247** [comment]
What about this part:

>>What I've noticed is the Media Sync will count up to around 150-190, then it seems to stop or timeout without producing other notifications or an error.

This seems like a bug. Any thoughts?

**Comment by fnya** [comment]
@g33k247 
I tried to reproduce this error with 1,035 notes (38,763 images) but could not reproduce it.

It may be improved in other versions.

If you can reproduce the error, please let us know,
From the Obsidian menu bar, click View >> Toggle Developer Tools.
If the error message is reproduced, please get the error message and create a new issue.

This issue will be closed.
