### ISSUE TITLE
Use the script on one note.

### ISSUE THREAD

**Issue by tonypuglieso** [fnya/media-sync#3]
Is it possible I can activate it for a single note? so I don't have to go through all the notes? Thank you very much for this plugin!

**Comment by fnya** [comment]
@tonypuglieso 
I'm thinking of implementing this one, but it looks like I won't be able to work on it for a while. 
Please wait for a while.

**Comment by fnya** [comment]
@tonypuglieso 
Implemented the feature of downloading images from right-click.
It is available in version 0.0.10, please try it.

Please check the README for instructions on how to use it.

**Comment by fnya** [comment]
@tonypuglieso
Implemented the feature of downloading images from right-click.
It is available in version 0.0.10, please try it.

Please check the README for instructions on how to use it.

**Comment by tonypuglieso** [comment]
Great! 😍

**Comment by tonypuglieso** [comment]
They work perfectly now 😀
