### ISSUE TITLE
Customized Image Download Path not saved

### ISSUE THREAD

**Issue by flowtec** [fnya/media-sync#4]
I could change the settings to store images from default to "Custom folder".
When i set the "Custom folder name" or "Osidian attachment folder", new media is stored under this folder.

But when i close Obsidian and start again the Setting "Folder to store images" is reset back to "Default".
Could you have a look again at this settings?

Obsidian: 1.4.16
Media Sync 0.0.11
OS: Tested with Ubuntu 22.04.3 and Windows 10

**Comment by fnya** [comment]
@flowtec 
This problem has been resolved in `0.0.12`, please try it.

**Comment by flowtec** [comment]
It is solved. That was quick - thank you!
