### ISSUE TITLE
Don't download

### ISSUE THREAD

**Issue by Rocoww** [fnya/media-sync#6]
Do not download the files. Even creates a destination noodles, but does not download. Does it work with other templates? Last time I used it was before changing the template and was working correctly

**Comment by pkej** [comment]
It worked for me the first time by pressing the "leaf" that's in the Ribbon, but the next time it didn't work. Even restarting Obsidian didn't work.

But the right click on file in the "Files" navigator worked and works.

**Comment by fnya** [comment]
@Rocoww 
I don't know about a template, but it may not work with a template because it is not designed for that.

**Comment by fnya** [comment]
@pkej 
Downloading from the leaf symbol is made to skip markdown files once downloaded.
 So, to force a download, you need to perform a right-click download as described.

**Comment by fnya** [comment]
This issue is closed.
